### ISSUE TITLE
Android : RejectedExecutionException Error when calling cup.suckUp

### ISSUE THREAD

**Issue by tiltmaster** [thangpn0207/tapioca_v2#1]
Hi, I have been running into an error when implementing any filter or text and then executing the below:

`cup.suckUp(path).then((_) {
  print("finish processing");
});`

and getting error as 
```E/System  ( 8392): Uncaught exception thrown by finalizer
E/System  ( 8392): java.util.concurrent.RejectedExecutionException: Task android.hardware.camera2.impl.CallbackProxies$SessionStateCallbackProxy$$ExternalSyntheticLambda0@6cff93b rejected from java.util.concurrent.ThreadPoolExecutor@31f4858[Terminated, pool size = 0, active threads = 0, queued tasks = 0, completed tasks = 3]
E/System  ( 8392):     at java.util.concurrent.ThreadPoolExecutor$AbortPolicy.rejectedExecution(ThreadPoolExecutor.java:2082)
E/System  ( 8392):     at java.util.concurrent.ThreadPoolExecutor.reject(ThreadPoolExecutor.java:842)
E/System  ( 8392):     at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1374)
E/System  ( 8392):     at java.util.concurrent.Executors$DelegatedExecutorService.execute(Executors.java:678)
E/System  ( 8392):     at android.hardware.camera2.impl.CallbackProxies$SessionStateCallbackProxy.onClosed(CallbackProxies.java:104)
E/System  ( 8392):     at android.hardware.camera2.impl.CameraCaptureSessionImpl.close(CameraCaptureSessionImpl.java:588)
E/System  ( 8392):     at android.hardware.camera2.impl.CameraCaptureSessionImpl.finalize(CameraCaptureSessionImpl.java:894)
E/System  ( 8392):     at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:339)
E/System  ( 8392):     at java.lang.Daemons$FinalizerDaemon.processReference(Daemons.java:324)
E/System  ( 8392):     at java.lang.Daemons$FinalizerDaemon.runInternal(Daemons.java:300)
E/System  ( 8392):     at java.lang.Daemons$Daemon.run(Daemons.java:145)
E/System  ( 8392):     at java.lang.Thread.run(Thread.java:1012)```

**Comment by thangpn0207** [comment]
@tiltmaster Can you show me full source add TapiocaBall and android config

**Comment by vipulthapliyal007** [comment]
I am also facing issue in this 
await cup.suckUp(pathNew);
its not giving any error
app gets stucked.
